SELECT TOP (1000) [DeployID]
      ,[CompanyID]
      ,[Description]
      ,[StartDate]
      ,[EndDate]
      ,[Active]
      ,[CreatedDate]
      ,[CreatedBy]
      ,[UpdatedDate]
      ,[UpdatedBy]
      ,[AppTypeID]
      ,[DeployGroupID]
      ,[Ordinal]
  FROM [IPAv5PackageDeploy].[dbo].[Deploy]