SELECT TOP (100) [PackageTypeID]
      ,[Type]
      ,[Description]
      ,[Active]
      ,[CreatedDate]
      ,[CreatedBy]
      ,[UpdatedDate]
      ,[UpdatedBy]
  FROM [IPAv5PackageDeploy].[dbo].[PackageType]